create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  category text not null,
  created_at timestamptz not null default now()
);

insert into public.products (name, price, category)
values
  ('Classic White T-Shirt', 19.99, 'Tops'),
  ('Blue Denim Jeans', 49.90, 'Bottoms'),
  ('Lightweight Jacket', 79.50, 'Outerwear')
on conflict do nothing;
